require File.join(RAILS_ROOT, 'lib', 'ext', 'action_view')
require File.join(RAILS_ROOT, 'lib', 'ext', 'action_controller')
require File.join(RAILS_ROOT, 'lib', 'ext', 'i18n')
require File.join(RAILS_ROOT, 'lib', 'ext', 'string_ext')
require File.join(RAILS_ROOT, 'lib', 'ext', 'slow_query')